### ISSUE TITLE
black sreen on watch

### ISSUE THREAD

**Issue by artron33** [ThaysPrado/Todo-App-with-Apple-Watch-Integration#1]
Hello,

When i'm installing the app on my iphone. I just got a an app with a black sreen on the watch.
I don't know why ? Is there a specific way to push the app on the watch ?

**Comment by ThaysPrado** [comment]
I didn't get a chance to test it with the actual Apple Watch.
When I was developing the project, for testing, I followed the steps below:

- Run the project on the Apple Watch simulator.
- Launch the simulator paired with the Apple Watch simulator.
- Run the entire project using the "flutter run" command.

This should be sufficient. While testing the steps, I noticed that it didn't work the first time, but it did work the second time.
If it doesn't work, please let me know.

**Comment by artron33** [comment]
Thanks for the precision ❤️
